#include "avg.h" /* header file generated by rpcgen */
#include <stdlib.h>

// usage instructions:
// specify ascending or descending as flag: '-a' or '-d' respectively

void averageprog_1(char *host, int argc, char *argv[])
{
   CLIENT *clnt; /* client handle, rpc.h included in avg.h from rpcgen */
   int i;
   double f, *dp;
   char *endptr;
   char flag[3];

   strcpy(flag, argv[argc - 1]);

   input_data average_1_arg, *result_1;

   average_1_arg.input_data.input_data_val = (double *)malloc(MAXAVGSIZE * sizeof(double));

   dp = average_1_arg.input_data.input_data_val;       /* pointer to double, beginning of input data */
   average_1_arg.input_data.input_data_len = argc - 2; /* set number of items */

   for (i = 1; i <= (argc - 2); i++)
   { /* str to d ASCII string to floating point nubmer */
      f = strtod(argv[i + 1], &endptr);
      printf("value   = %e\n", f);
      *dp = f;
      dp++;
   }

   clnt = clnt_create(host, AVERAGEPROG, AVERAGEVERS, "udp");

   if (clnt == NULL)
   {
      clnt_pcreateerror(host);
      exit(1);
   }

   result_1 = average_1(&average_1_arg, clnt);

   if (result_1 == NULL)
   {
      clnt_perror(clnt, "call failed:");
   }

   clnt_destroy(clnt);

   dp = result_1->input_data.input_data_val;

   char a_flag[] = "-a";
   char d_flag[] = "-d";

   // check if the ascending flag was used
   if (strcmp(flag, a_flag) == 0)
   {
      // print array in order recieved from rpc, array is always received in ascending order
      for (i = 0; i < (argc - 3); i++)
      {
         printf("%e ", *dp);
         dp++;
      }
   }

   // move dp to end of returned array
   for (i = 1; i < (argc - 3); i++) //
   {
      dp++;
   }

   // check if descending flag was used
   if (strcmp(flag, d_flag) == 0)
   {
      // print array in reverse order by decrementing dp, since array is received in ascending order, reversing will print it in descending order
      for (i = 0; i < (argc - 3); i++)
      {
         printf("%e ", *dp);
         dp--;
      }
   }

   printf("\n");
}

/* here is main */
main(int argc, char *argv[])
{
   char *host;

   if (argc < 3)
   {
      printf("usage: %s server_host value ...\n", argv[0]);
      exit(1);
   }

   if (argc > MAXAVGSIZE + 2)
   {
      printf("Two many input values\n");
      exit(2);
   }

   /* host name is in first parameter (after program name) */
   host = argv[1];
   averageprog_1(host, argc, argv);
}
